### ISSUE TITLE
Slurm batch effects

### ISSUE THREAD

**Issue by micknudsen** [micknudsen/gwf-utilization#8]
Even though one of your jobs has Slurm JobID `XXXXXX`, that doesn't prevent other users from having (batch?) jobs called `XXXXXX_1`, `XXXXXX_2`, `XXXXXX_3` etc, and these will show up in the `utilization` output, too.

**Comment by dansondergaard** [comment]
The underscored job ids are caused by job arrays. Since *gwf* doesn't support job arrays (that is, it never submits a job array itself), you can assume that those jobs do not belong to the workflow and filter them out.
